// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwLh5c-23Q_BwQzzj1mqJqqM-1yBn8oE8',
    appId: '1:257558773244:web:74cad99a76daabc2438679',
    messagingSenderId: '257558773244',
    projectId: 'ecommerce-d0b69',
    authDomain: 'ecommerce-d0b69.firebaseapp.com',
    storageBucket: 'ecommerce-d0b69.appspot.com',
    measurementId: 'G-EDHCSGNNW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyagnFVPFZ64Bh8OV1qdw1zmUTViLmM0M',
    appId: '1:257558773244:android:af646f66423cad11438679',
    messagingSenderId: '257558773244',
    projectId: 'ecommerce-d0b69',
    storageBucket: 'ecommerce-d0b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD0M8pcHUuEkTXscAWltpy0_0mkUkWs_Q',
    appId: '1:257558773244:ios:908d700f71219098438679',
    messagingSenderId: '257558773244',
    projectId: 'ecommerce-d0b69',
    storageBucket: 'ecommerce-d0b69.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD0M8pcHUuEkTXscAWltpy0_0mkUkWs_Q',
    appId: '1:257558773244:ios:908d700f71219098438679',
    messagingSenderId: '257558773244',
    projectId: 'ecommerce-d0b69',
    storageBucket: 'ecommerce-d0b69.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwLh5c-23Q_BwQzzj1mqJqqM-1yBn8oE8',
    appId: '1:257558773244:web:56f53aae904987f9438679',
    messagingSenderId: '257558773244',
    projectId: 'ecommerce-d0b69',
    authDomain: 'ecommerce-d0b69.firebaseapp.com',
    storageBucket: 'ecommerce-d0b69.appspot.com',
    measurementId: 'G-GT8P44GZG7',
  );
}
